### ISSUE TITLE
Maui app won't build after upgrading .net sdk to 8.0.201

### ISSUE THREAD

**Issue by mmiller-d8** [getsentry/sentry-dotnet#3279]
### Package

Sentry.Maui

### .NET Flavor

Xamarin

### .NET Version

8.0.201

### OS

iOS

### SDK Version

4.2.1

### Steps to Reproduce

1. Upgrade the .net sdk to 8.0.201
2. Create a new Maui project
3. Build and observe that it builds
4. Add a reference to Sentry.Maui
5. Build
6. Observe that bad things happen (the build fails)
7. Remove the reference to Sentry.Maui
8. Build
9. Observe that the build works again

### Expected Result

The project builds and deploys to the emulator

### Actual Result

The build fails with the following error:

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
Undefined symbols for architecture x86_64:
  "_SentryVersionNumber", referenced from:
     -exported_symbol[s_list] command line option
  "_SentryVersionString", referenced from:
     -exported_symbol[s_list] command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation) (SentryBuildError)

**Comment by mmiller-d8** [comment]
As an aside, this is a fatal error for me.  I'm going to have to completely remove Sentry from my project until this is resolved.

Also, this error does not occur with my .net core api project.  It's just Maui.

**Comment by tbaggett** [comment]
+1, and we've been using 8.0.201 for several weeks without issue. MSFT pushed workload updates yesterday that changed things for 8.0.201

**Comment by thomasbach-dk** [comment]
Same issue here. Seems like a [fix](https://github.com/getsentry/sentry-dotnet/issues/3233) is on it´s way very soon.

**Comment by bitsandfoxes** [comment]
Hey there! Sorry about that. The bindings have been fixed here: https://github.com/getsentry/sentry-dotnet/pull/3278
A release is coming any minute now.

**Comment by bitsandfoxes** [comment]
Thanks for your patience! Fixed in `4.3.0`.

**Comment by mmiller-d8** [comment]
I appreciate the rapid response @bitsandfoxes
